#####
#Soubor: makefile
#Autor: Jan Wrona, xwrona00@stud.fit.vutbr.cz
#Datum: 15.04.2012
#Projekt: Projekt c. 4 pro predmet ITY
#####

NAME=itu

latex: $(NAME).tex
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex

clean:
	rm -f $(NAME).aux $(NAME).log $(NAME).out $(NAME).toc
